version: '3'

services:
  api:
    container_name: api_container
    tty: true
    build:
      context: .
      dockerfile: docker/go/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./src:/app
  db:
    container_name: db_container
    build: 
      context: .
      dockerfile: docker/db/Dockerfile
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: example_db
    restart: always